@startuml
left to right direction
skin rose

:Worker: as wk
usecase "Add item" as add
usecase "Update item" as up
usecase "Delete item" as del
usecase "Show items" as show

wk -- add
wk -- up
wk -- del
wk -- show

@enduml